language: node_js

node_js:
  - "lts/*"
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - "npm test"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - ram@hiddentao.com
